Vsl30 del 435 bulk delete attachments
asseco-voice/laravel-attachments pull request #39
Opened 2024-08-01 14:13 UTC by DevFajdetic

2024-08-01 14:33 UTC, DaveXo9 commented
@DevFajdetic  pogledaj PR pipe

2024-08-02 09:05 UTC, ngaspari requested changes
pokriti failed scanarios on deletion

2024-08-02 09:05 UTC, ngaspari commented on src/App/Http/Controllers/AttachmentController.php
> +            Log::error('Failed to bulk delete attachments', [
Trebalo bi pokrit slučaj ako se neki attachment uspije obrisat, a neki ne.....
Vratit listu:  deleted: [],  failed: []
dakle, ne loop u try/catch,  već try/catch u loopu

2024-08-02 09:49 UTC, ngaspari approved these changes

2024-08-02 09:57 UTC, merged